[[main]]
name = "À propos"
url = "/#about"
weight = 2

[[main]]
name = "Compétences"
url = "/#skills"
weight = 3

[[main]]
name = "Expérience"
url = "/#experience"
weight = 4

[[main]]
name = "Contact"
url = "/#contact"
weight = 5

[[main]]
name = "Tech Stack"
url = "/#technical"
weight = 4.5

[[main]]
name = "Blog"
url = "/fr/blog/"
weight = 60

[[main]]
name = "Ingénierie"
url = "/fr/engineering/"
weight = 50
pre = "engineering"

[[main]]
name = "Contributions"
url = "/fr/contributions/"
weight = 51
pre = "contributions"

