# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
identifier = "archives"
pre = ""
post = ""
name = "Archives"
url = "/archives/"
title = ""
weight = 1

[main.params]
# icon = "fa-solid fa-archive"
icon = "fa-solid fa-feather"

[[main]]
identifier = "categories"
parent = "archives"
pre = ""
post = ""
name = "Categories"
url = "/categories/"
title = ""
weight = 2

[main.params]
icon = "fa-solid fa-folder-tree"

[[main]]
identifier = "collections"
parent = "archives"
pre = ""
post = ""
name = "Collections"
url = "/collections/"
title = ""
weight = 3

[main.params]
icon = "fa-solid fa-layer-group"

[[main]]
identifier = "tags"
parent = "archives"
pre = ""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 3

[main.params]
icon = "fa-solid fa-tags"

[[main]]
identifier = "fixit"
parent = "archives"
pre = '<img class="fixit-icon" src="https://fixit.lruihao.cn/images/hugo-fixit.webp" alt="FixIt logo">'
post = '<i class="fa-solid fa-external-link-alt fa-fw fa-xs text-secondary"></i>'
name = "FixIt"
url = "https://fixit.lruihao.cn/"
title = "FixIt"
weight = 4

[main.params]
divided = true

[[main]]
identifier = "projects"
pre = ""
post = ""
name = "Projects"
url = "/projects/"
title = "Projects"
weight = 4

[main.params]
# icon = "fa-solid fa-code-branch"
icon = "fa-solid fa-lightbulb fa-shake"

[[main]]
identifier = "friends"
pre = ""
post = ""
name = "Friends"
url = "/friends/"
title = "Friends"
weight = 5

[main.params]
icon = "fa-solid fa-users"

[[main]]
identifier = "reward"
pre = ""
post = ""
name = "Rewards"
url = "/reward/"
title = ""
weight = 6

[main.params]
icon = "fa-solid fa-hand-holding-dollar"

[[main]]
identifier = "guestbook"
pre = ""
post = ""
name = "Guest Book"
url = "/guestbook/"
title = ""
weight = 7

[main.params]
icon = "fa-solid fa-comment-dots"

[[main]]
identifier = "rss"
pre = ""
post = ""
name = "RSS"
url = "/index.xml"
title = "RSS"
weight = 8

[main.params]
icon = "fa-solid fa-rss"
type = "desktop"

[[main]]
identifier = "about"
pre = ""
post = ""
name = "About"
url = "/about/"
title = ""
weight = 100

[main.params]
icon = "fa-solid fa-quote-left"

[[main]]
identifier = "github"
pre = ""
post = ""
name = "Follow"
url = "https://github.com/Lruihao/"
title = ""
weight = ""

[main.params]
class = "text-center"
icon = "fa-brands fa-github fa-lg"
type = "mobile"
