# -------------------------------------------------------------------------------------
# Front Matter Configuration
# See: https://gohugo.io/configuration/front-matter/
# -------------------------------------------------------------------------------------

lastmod = ["lastmod", ":fileModTime", ":git", ":defalut"]
